<a href="https://colab.research.google.com/github/hairishbabucse273/CSE-237_Exercise_Collection/blob/main/CSE273_Exercise03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
s = pd.Series([10,20,30,40,50])
print(s)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [ ]:
s = pd.Series([10,20,30 ], index = ["a", "b" , "c"])
print(s)

a    10
b    20
c    30
dtype: int64

In [ ]:
data = {"Math":90,"Physics":85,"Chemistry":88}
marks = pd.Series(data)

In [ ]:
print(data)

{'Math': 90, 'Physics': 85, 'Chemistry': 88}

In [ ]:
data = {
    "Name": ["Amani", " Krish" , " Karan" ],
    "Age": [22, 33, 21],
    "Marks": [85, 90,88]
}

In [ ]:
print(data)

{'Name': ['Amani', ' Krish', ' Karan'], 'Age': [22, 33, 21], 'Marks': [85, 90, 88]}

In [ ]:
marks = pd.DataFrame(data)

In [ ]:
print(marks)

     Name  Age  Marks
0   Amani   22     85
1   Krish   33     90
2   Karan   21     88

In [ ]:
marks = pd.DataFrame(
    data,
    index = ["Student1","Student2","Student3"]
)

In [ ]:
print(marks)

            Name  Age  Marks
Student1   Amani   22     85
Student2   Krish   33     90
Student3   Karan   21     88

In [ ]:
marks.set_index("Name", inplace=True)

In [ ]:
print(marks)

        Age  Marks
Name
Amani    22     85
 Krish   33     90
 Karan   21     88

In [ ]:
df = pd.DataFrame({
    "Name":["Alice", "Bob", "Charles"],
    "Age":[25,30,35],
    "Marks":[84,90,88]
})

In [ ]:
print(df)

      Name  Age  Marks
0    Alice   25     84
1      Bob   30     90
2  Charles   35     88

In [ ]:
df.head()

      Name  Age  Marks
0    Alice   25     84
1      Bob   30     90
2  Charles   35     88

In [ ]:
df.head(2)

    Name  Age  Marks
0  Alice   25     84
1    Bob   30     90

In [ ]:
df.tail(2)

      Name  Age  Marks
1      Bob   30     90
2  Charles   35     88

In [ ]:
df.describe()

        Age      Marks
count   3.0   3.000000
mean   30.0  87.333333
std     5.0   3.055050
min    25.0  84.000000
25%    27.5  86.000000
50%    30.0  88.000000
75%    32.5  89.000000
max    35.0  90.000000

In [ ]:
df["Name"]

0      Alice
1        Bob
2    Charles
Name: Name, dtype: object

In [ ]:
df[["Name","Marks"]]

      Name  Marks
0    Alice     84
1      Bob     90
2  Charles     88

In [ ]:
df[df["Marks"]>85]

      Name  Age  Marks
1      Bob   30     90
2  Charles   35     88

In [ ]:
df[(df["Age"]>21)&(df["Marks"]>85)]

      Name  Age  Marks
1      Bob   30     90
2  Charles   35     88

In [ ]:
df.sort_values("Marks")

      Name  Age  Marks
0    Alice   25     84
2  Charles   35     88
1      Bob   30     90

In [ ]:
df.sort_values("Marks", ascending = False)

      Name  Age  Marks
1      Bob   30     90
2  Charles   35     88
0    Alice   25     84

In [ ]:
df["Age"].value_counts()

Age
25    1
30    1
35    1
Name: count, dtype: int64

In [ ]:
df = pd.DataFrame({
"Name": ["Aman", "Karan", "Shubham", None, "Sammer"],
"Age": [22,23,None,22,25],
"Marks": [85,None,88,90,56]
})
df

      Name   Age  Marks
0     Aman  22.0   85.0
1    Karan  23.0    NaN
2  Shubham   NaN   88.0
3     None  22.0   90.0
4   Sammer  25.0   56.0

In [ ]:
df.isnull()

    Name    Age  Marks
0  False  False  False
1  False  False   True
2  False   True  False
3   True  False  False
4  False  False  False

In [ ]:
df.isnull().sum()

Name     1
Age      1
Marks    1
dtype: int64

In [ ]:
print(df)

      Name   Age  Marks
0     Aman  22.0   85.0
1    Karan  23.0    NaN
2  Shubham   NaN   88.0
3     None  22.0   90.0
4   Sammer  25.0   56.0

In [ ]:
df.dropna()

     Name   Age  Marks
0    Aman  22.0   85.0
4  Sammer  25.0   56.0

In [ ]:
cleaned_data = df.dropna()

In [ ]:
cleaned_data

     Name   Age  Marks
0    Aman  22.0   85.0
4  Sammer  25.0   56.0